# Generated by Django 6.1.1 on 2026-09-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=10)),
                ('stu_id', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_phone', models.IntegerField()),
                ('stu_course', models.CharField()),
                ('stu_year', models.IntegerField()),
                ('stu_admission_date', models.DateField()),
                ('stu_status', models.BooleanField(default=True)),
            ],
        ),
    ]
