# Generated by Django 6.1.1 on 2026-09-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('duration', models.CharField()),
                ('fee', models.CharField()),
                ('trainer_name', models.CharField(max_length=100)),
                ('mode_onlineoffline', models.CharField()),
                ('start_date', models.DateField()),
                ('noof_seats', models.CharField()),
                ('course_status', models.CharField()),
            ],
        ),
    ]
